apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: observability
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-gateway
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  endpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 15s
      scheme: http
